/** 
* Unpublished Work. Copyright 2009-2018 Transverse, LLC. All Rights Reserved.
* This software contains confidential and trade secret information of:
* Transverse, LLC.
* 620 Congress Ave.
* Suite 200
* Austin, TX 78701
* USA
* Use, duplication or disclosure of this software is prohibited
* without prior written permission of Transverse, LLC.
*/

/*******************************************************************************************************************
** Module Name   : GlobalGTVActions
** 
**
** Revision History:-
** Version             Date            Author                Description of Action:
** 1.0                 22/03/2020      AMAN JAIN             This class has been depprecated and not used further
******************************************************************************************************************************/
@deprecated 
global with sharing class GlobalGTVActions {
    
        @deprecated 
   global static void createBillingAccount(string accountId){
   }
    @deprecated 
    global static String createGTVOrder(String OpportunityId){
        return null;
    }
    @deprecated 
    global static void createGotransverseSalesOrder(Map <String, String> orderInformation){}
     @deprecated
    global static void createOrderApex(String OpportunityId){}
        @deprecated 
    global static void createGotransverseDraftOrder(Map <String, String> orderInformation){
        
       
    }
       
    }