/**
 * Unpublished Work. Copyright 2009-2018 Transverse, LLC. All Rights Reserved.
 * This software contains confidential and trade secret information of:
 * Transverse, LLC.
 * 620 Congress Ave.
 * Suite 200
 * Austin, TX 78701
 * USA
 * Use, duplication or disclosure of this software is prohibited
 * without prior written permission of Transverse, LLC.
 */

/**
 * The service resource query response wrapper.
 * @author AMAN JAIN
 */
global class GTVServiceResource {
  public String id { get; set; }
  public String identifier { get; set; }
  public String description { get; set; }
  public String resourceCategoryId { get; set; }
}